name: Try git-pr-release

on: push
  # push:
  #   branches:
  #     - develop

jobs:
  git-pr-release:
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    env:
      GIT_PR_RELEASE_BRANCH_PRODUCTION: master
      GIT_PR_RELEASE_BRANCH_STAGING: develop
      GIT_PR_RELEASE_TOKEN: ${{ secrets.GIT_PR_RELEASE_TOKEN }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Asia/Tokyo

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: install git-pr-release gem
      run: gem install git-pr-release

    - name: create release pr
      run: git-pr-release
